### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by pedrouid** [balance-io/balance-manager#171]

**Comment by amhed** [comment]
How much do we wish to test?
- Only on reducers?
- Inspecting DOM elements after render using a library like Enzyme?

I assume that: 
- This task is only to setup the basic infrastructure to get tests running, and that
- After initials config done/examples created we will create independent issues for coverage on specific parts of the code
- We will also have an issue for running tests on the CI + making tests mandatory for future contributions (I feel really uneasy committing untested code)

**Comment by pedrouid** [comment]
I already started on this, check the ‘tests’ branch

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pedrouid** [comment]
I want to start with the ‘helpers’ folder then move onto ‘handlers’

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by amhed** [comment]
👌 Will love to take on some test coverage after you land first examples/conventions

**Comment by amhed** [comment]
On second thought, since you haven't touched the unit tests branch in a few days, you mind if I add additional coverage so we have a baseline? I can start working on the `helpers` folder.

**Comment by pedrouid** [comment]
There are a lot of changes and refactoring happening right now, I'm not going to prioritise this until those come into effect
