### ISSUE TITLE
Getting prices from same symbol conflicts

### ISSUE THREAD

**Issue by pedrouid** [balance-io/balance-manager#176]
[Reported by user through Intercom]

![000001](https://user-images.githubusercontent.com/10136079/39774726-b69e8948-52c9-11e8-9daf-186ea933191e.jpg)
![000002](https://user-images.githubusercontent.com/10136079/39774727-b6ac6de2-52c9-11e8-8275-0e2ae8a20caf.png)

**Comment by jinchung** [comment]
Will be addressed with issue: https://github.com/balance-io/balance-manager/issues/339
