### ISSUE TITLE
🔐 Security Audit

### ISSUE THREAD

**Issue by ricburton** [balance-io/balance-manager#197]
The only thing I fear more than cows (long story) is harming our customers. We need to get several external audits on our code to make sure we are doing everything possible to protect our customers.

**Comment by ricburton** [comment]
We should set something up on HackerOne: https://www.hackerone.com/

**Comment by ricburton** [comment]
One of our crowdfunders, https://twitter.com/ikoniaris, is looking into this for us.

**Comment by jinchung** [comment]
Done with Cure53.
