### ISSUE TITLE
💸 Donation Option

### ISSUE THREAD

**Issue by ricburton** [balance-io/balance-manager#200]
Idea sparked off by a conversation with Dan Held: Allow people to donate and vote on what feature they want next.

**Comment by mirshko** [comment]
Whats the idea for this? ETH Address for donations? USD? 

Also how would voting be organised?

**Comment by samelliott89** [comment]
Proposed idea for donation piece. Not 100% loving where I've put "Donate" button, perhaps @ricburton you could give some guidance. But imagining this pulls up the exchange modal to accept ETH donations. Recipient address would be pre-populated. Also default to "Slow".

<img width="1040" alt="screen shot 2018-05-15 at 8 43 34 pm" src="https://user-images.githubusercontent.com/6912845/40095574-a45c95d2-5881-11e8-874b-4b7ed42f60a1.png">

**Comment by ricburton** [comment]
@mirshko not sure right now. Just exploring.

@samelliott89 love this! 

@christianbaroni, what do you think of something like this? Perhaps a little less prominent?

**Comment by ricburton** [comment]
Also the recipient address should be known. It'll be us :)

**Comment by samelliott89** [comment]
@ricburton Yes, that will be pre-populated with your ETH address of choice. Implementation wise, was going to create a new, reduced version of SendModal instead of overriding the existing one?

**Comment by mirshko** [comment]
It could also be done with a prop of the donation Eth address sent into the
SendModal component instead of adding more code 😉

**Comment by samelliott89** [comment]
@mirshko I'm all for that 👍 The piece I'm struggling with is all modals are called (quite nicely) like so:

 ```javascript
modalController = () => {
    switch (this.props.modal) {
      case 'EXCHANGE_MODAL':
        return <ExchangeModal />;
      case 'SEND_MODAL':
        return <SendModal />;
      case 'RECEIVE_MODAL':
        return <ReceiveModal />;
      case 'WALLET_CONNECT_INIT':
        return <WalletConnectInit />;
      default:
        return <div />;
    }
  };
```
and then populated based on redux state. Perhaps on Donate button press I could update some sort of redux state and have that populate SendModal with the ETH address (let me know if this is what you mean...)

I'm being cautious here as I want to adhere to your implementation style :)

**Comment by pedrouid** [comment]
Hi @samelliott89, I used to have custom props that I called `modalProps` on the `_modal.js` reducer that allowed to populate the modal, the disadvantage of this approach was that it produced a snapshot of the state at the moment the modal was opened, this could be improved by having an action to update `modalProps` by using the `componentDidUpdate` at the origin of these modals.
However I don't think this should be an issue for the Donation modal but I also think this should definitely be it's own modal even if it shares the same reducer as the `SendModal`

**Comment by pedrouid** [comment]
```
// -- Constants ------------------------------------------------------------- //

const MODAL_OPEN = 'modal/MODAL_OPEN';
const MODAL_CLOSE = 'modal/MODAL_CLOSE';

// -- Actions --------------------------------------------------------------- //

export const modalOpen = (modal, props) => ({
  type: MODAL_OPEN,
  payload: { modal, props },
});

export const modalClose = () => ({ type: MODAL_CLOSE });

// -- Reducer --------------------------------------------------------------- //
const INITIAL_STATE = {
  modal: '',
  modalProps: {}
};

export default (state = INITIAL_STATE, action) => {
  switch (action.type) {
    case MODAL_OPEN:
      return { ...state, modal: action.payload.modal, modalProps: action.payload.props };
    case MODAL_CLOSE:
      return { ...state, modal: '',   modalProps: {} };
    default:
      return state;
  }
};
```

**Comment by pedrouid** [comment]
This way you can map these modalProps into the `DonationModal` and use the props given by the `modalOpen` action creator

**Comment by samelliott89** [comment]
<img width="1195" alt="screen shot 2018-05-18 at 8 01 20 pm" src="https://user-images.githubusercontent.com/6912845/40264375-f53f1676-5ad6-11e8-8623-e936a0a6be76.png">

@pedrouid @ricburton have a working version. Will need an ETH address from you guys to collect donations before I can submit a PR. :)

**Comment by ricburton** [comment]
This is amazing! Thank you. Please add this address: 0x8F12DA507508138993EB3BAA610D18E036cD9936
