### ISSUE TITLE
$MAN doesn't sum up

### ISSUE THREAD

**Issue by fccbb** [balance-io/balance-manager#201]
hi there I'm having an issue with the $MAN token, it displays my holding but the sum is buggy:

![screenshot 37](https://user-images.githubusercontent.com/30546271/39969705-40a9ec62-56e0-11e8-95c1-1d7de8f9e467.png)

**Comment by ricburton** [comment]
Can you DM me your Ethereum address?

**Comment by fccbb** [comment]
I sent you a @

**Comment by christianbaroni** [comment]
To clarify, it's the price that's wrong—on CoinMarketCap it's $1.20.

**Comment by fccbb** [comment]
right, I didn't think to check CMC cheers then I'll have to wait.

**Comment by fccbb** [comment]
for info CMC is not a reliable source, they have been known to alter results:
[https://medium.com/@coinmarketcapped/intro-how-coinmarketcap-cmc-manipulates-the-market-by-showing-fraudulent-information-to-the-c1246a953144](https://medium.com/@coinmarketcapped/intro-how-coinmarketcap-cmc-manipulates-the-market-by-showing-fraudulent-information-to-the-c1246a953144)

**Comment by ricburton** [comment]
Totally agree. We need price oracles.

However, users get confused. Perhaps we should list CMC and then all the exchanges explicitly when you click on the asset.

Will think more on this.

Richard

Sent via Superhuman ( https://sprh.mn/?vip=richard@balance.io )

**Comment by christianbaroni** [comment]
Another report:

![6c191958-0c4a-483a-92d9-4a90da123363](https://user-images.githubusercontent.com/7061887/40630390-bbcd5446-62a8-11e8-9ab7-200c5df14a11.png)

Oddly it looks like the ETH price is correct from CryptoCompare.
