### ISSUE TITLE
⚫️ Shadow + Line + Rounded Rec looks 🤢

### ISSUE THREAD

**Issue by ricburton** [balance-io/balance-manager#220]
<img width="24" alt="screen shot 2018-05-15 at 05 07 05" src="https://user-images.githubusercontent.com/438160/40047606-eb465ff2-57fd-11e8-9121-b2e4688be7d5.png">

This shadowed rounded rec and the lines above and below don't look smooth. @christianbaroni perhaps it could animate away the lines above and below?

**Comment by ricburton** [comment]
<img width="141" alt="screen shot 2018-05-15 at 05 09 11" src="https://user-images.githubusercontent.com/438160/40047679-1f4dafd0-57fe-11e8-8afc-0629be80f04c.png">

**Comment by mirshko** [comment]
Where is this on the UI? Bigger scope screenshot with callout would be nice :)
