### ISSUE TITLE
✉️ Email Submission Bug

### ISSUE THREAD

**Issue by ricburton** [balance-io/balance-manager#232]
It overflows on mobile. Needs work. Will
Upload screenshot.

**Comment by ricburton** [comment]
https://spectrum.imgix.net/threads/8dac1cbb-a8f8-43d6-a524-1d15cd6fca48/ryQeXcxk7-7F340299-A47A-4056-A633-43973FFE60CB.png?max-w=768

**Comment by mikedemarais** [comment]
I fixed this in this PR https://github.com/balance-io/balance-manager/pull/243
