### ISSUE TITLE
Can submit a transaction with 0 or "nothing" as the value

### ISSUE THREAD

**Issue by samelliott89** [balance-io/balance-manager#237]
### What is this issue about? (select one)

* [ ] Bug report

### Issue Description

You can send a transaction with a value of 0 or "nothing". Is this intentional? 

## Steps to reproduce

1. Open Send Modal
2. Submit a transaction with 0 value.

<img width="1005" alt="screen shot 2018-05-21 at 8 15 36 pm" src="https://user-images.githubusercontent.com/6912845/40340486-f8c34100-5d33-11e8-868f-2d4e20287ae2.png">

**Comment by pedrouid** [comment]
Yes, it's should be totally allowed even if redundant
One scenario for example is on Ropsten testnet you can get Status Test Tokens by sending 0 value to their faucet.

However thanks for reporting the Bug, that infamous NaN shouldn't be there!

**Comment by samelliott89** [comment]
I see. What about "no value". i.e null/empty string etc.?

**Comment by jinchung** [comment]
hi @samelliott89 - thanks for the report. If I understand you correctly, your last question may be related to this issue: https://github.com/balance-io/balance-manager/issues/252. If it's covered in there, I'll close this issue for now.

**Comment by samelliott89** [comment]
@jinchung yes you can close.
