### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by tomjohnburton** [balance-io/balance-manager#241]
### What is this issue about? (select one)

* [X ] Bug report
* [ ] Feature request
* [ ] Enhancement

### Issue Description

Error received while attempting to make an exchange. Error did not affect the actual purchasing process. 

Also I typed 0.03 ETH by accident and quickly changed to 0.3 ETH. However the ZRX conversion did not update to the new amount.

<img width="828" alt="screenshot 2018-05-23 14 11 34" src="https://user-images.githubusercontent.com/39559415/40426958-48dfce18-5e94-11e8-873b-961ee9876f89.png">

## Steps to reproduce

Quickly change from one amount to another

**Comment by jinchung** [comment]
@pedrouid found that this was due to requesting shifts that don't make sense (like '0' or '0.') that occur when typing out and updating the input fields. The fix will be pushed soon, and I'll update here with the PR. Thanks for the report!
