### ISSUE TITLE
Dropdown menus shows unnecessary padding

### ISSUE THREAD

**Issue by amhed** [balance-io/balance-manager#246]
### What is this issue about? (select one)

* [X] Bug report
* [ ] Feature request
* [ ] Enhancement

### Issue Description

Dropdown menus shows unnecessary padding

![image](https://user-images.githubusercontent.com/579291/40572685-0e290d6c-6078-11e8-8bb3-d9a9b4de435a.png)

## Steps to reproduce

Running Chrome Version 66.0.3359.181 (Official Build) (64-bit) on OSX 10.13.4

**Comment by pedrouid** [comment]
I can't reproduce this in any of my branches? (tried `production`, `latest` and `shapeshift`)

**Comment by amhed** [comment]
I'm getting it on production. Perhaps I'm running a Chrome Addon that's interfering with it

![image](https://user-images.githubusercontent.com/579291/40578358-5f3ed988-60d8-11e8-90e6-59c1c6614f1b.png)

**Comment by pedrouid** [comment]
Inspect the page and see what css rule is causing it, you can probably tell which extension is doing it from that.

Also try to develop on Incognito mode by enabling Metamask

**Comment by amhed** [comment]
In incognito: 
![image](https://user-images.githubusercontent.com/579291/40578912-5aeeaf52-60e2-11e8-8933-7e962948af7f.png)

Tried it on Windows. It renders scrolls. I think this can be easily fixed with `overflow: hidden` instead of scrolls (the list is short enough that we don't need it).

Still I'm curious why it would happen on my machine only, even with no plugins enabled/incognito 🤔

**Comment by pedrouid** [comment]
That's very strange, I can't seem to replicate on my side.

However we should split the overflow for x and y because this component will be used around the app and it will have more than 5-6 items

```
  overflow-x: hidden;
  overflow-y: scroll;
```

**Comment by amhed** [comment]
Set it to auto so it adds scrolls whenever the div grows too much
