### ISSUE TITLE
Token curated registry

### ISSUE THREAD

**Issue by benjiqq** [balance-io/balance-manager#248]
quote from @pedrouid "PROPOSAL: What we REALLY need is to create Token Curated Registry, or a more pragmatic approach, a repository with matching token symbols/names to their contract addresses. This would solve two majors issues:

conflitcing prices with tokens of the same symbol/ticker
tokens trying to mimic or impersonate popular tokens (like @benjyz was mentioning)"

This is a big project currently not addressed in the Ethereum ecosystem for various reasons. I would distinguish between 
1) a central register maintained by a single entity (etherscan, coinmarketcap, exchange) 
2) a central register maintained by a group of people with a decentral/distributed process 
3) a generally accepted register on-chain

2 can be first approximated with a github based process.Whitelists, Blacklists and other mechanisms should be as modular as possible, so that the consensus for now focuses on "address" => "Symbol" mapping. With regards to 3) the way I would judge current consensus is that Eth core has no need for this, see EIP-740.

Sources and tangential projects: etherscan, coinmarketcap, cryptocompare, exchanges, ENS, ...
Links:
https://medium.com/@ConsenSys/regis-the-decentralized-registry-5fb89655219a
https://github.com/ethereum/EIPs/issues/740
https://etherscan.io/tokens

**Comment by benjiqq** [comment]
Some argument against a "central register" are along the lines of anyone can choose who they trust and there shouldn't be a default. However a name resolution mechanism requires that it is global otherwise it is useless. This patterns applies broadly. A blockchain ledger pointing to any real world asset requires acceptance. If everyone on the Internet does not agree that "google.com" refers to Google Inc. servers, it can be squatted, abused, etc. Similarly a transaction of "Google Stock" requires a unified mechanism. The solution 2 and 3 are far more desirable than 1. Having no standard will lead to some single central party providing the service.

**Comment by benjyz** [comment]
As I understand one goal of balance is to integrate various parts of the ethereum stack to make things easy and useable. In ethereum assets are really access to certain contract functions. Assets are defined by the contract code in terms of execution. On top of that there exist human readable terms or concepts, i.e. symbols. An asset definition is not the same as the asset itself. Asset definition registries (ADR) is something I define as a curated list of asset pointers, namely a hash to symbol mapping. This concept can be expanded to include asset types (erc20, erc721, ...), so one can talk about assets of being type. For now an ADR can be managed in a curation process on github.

For now in practical terms this simply means aggregating previous registries e.g. from forkdelta and making the terms and definitions more explicit. Etherscan is not sufficient and rigorous enough.

**Comment by ricburton** [comment]
I love this overview. We are partnering with TheGraph.com ( http://thegraph.com/ ) to help us with some of this. They contacted me after reading this post: https://medium.com/balance-io/open-protocol-interfaces-b1e631e41777

Richard

Sent via Superhuman ( https://sprh.mn/?vip=richard@balance.io )

**Comment by jinchung** [comment]
Will close this for now given that this project should be separate from our work.
