### ISSUE TITLE
500 ERROR

### ISSUE THREAD

**Issue by ricburton** [balance-io/balance-manager#255]
What causes this kind of error?
<img width="412" alt="screen shot 2018-05-29 at 10 53 59" src="https://user-images.githubusercontent.com/438160/40651872-b55fcacc-632e-11e8-8996-adcee0e82120.png">

**Comment by jinchung** [comment]
That's an internal service error from something on the server side. 
Is this recurrent or do you know what the context was around it when it occurred? This issue may be resolved for now. I'll close this, and let us know if you see it again, and what you were doing at the time.
