### ISSUE TITLE
💵 Allow people to donate tokens

### ISSUE THREAD

**Issue by ricburton** [balance-io/balance-manager#256]
I want all the gifts. Even the shit ones.

**Comment by kamescg** [comment]
Planning a "Token Toilet" project?

> We BUIDL and PITCH a project called Token Toilet (lets you flush unwanted, garbage tokens down the drain and lets people buy grab bags of flushed tokens for 5 DAI which goes to charity)

https://medium.com/@fgoldberg/hackathon-at-ethbuenosaires-updates-af66c84db798

**Comment by ricburton** [comment]
Haha love it :)

Richard

Sent via Superhuman ( https://sprh.mn/?vip=richard@balance.io )

**Comment by samelliott89** [comment]
This should be a small change to the current Donate ETH flow.

**Comment by samelliott89** [comment]
P.S. I'll take this once #257 is merged.
