### ISSUE TITLE
📱 Expose the WalletConnect option

### ISSUE THREAD

**Issue by ricburton** [balance-io/balance-manager#265]
We should show this in the user interface now so people can start learning about the WalletConnect project.

@pedrouid What do you think?

**Comment by pedrouid** [comment]
We can do, there is still a tricky part in terms of the session expiration.
@jinchung Maybe don't persist the session on localstorage for now

**Comment by ricburton** [comment]
Let's start with a simple explanation. That should get people curious to learn more about @walletconnect.

<img width="1048" alt="screen shot 2018-06-12 at 11 13 57" src="https://user-images.githubusercontent.com/438160/41300513-e90aefd6-6e33-11e8-811f-62355c96c1ee.png">
