### ISSUE TITLE
🇧🇷 Brazilian Translations

### ISSUE THREAD

**Issue by abstractpoint** [balance-io/balance-manager#276]
### What is this issue about? (select one)
* [x] Enhancement

**Comment by abstractpoint** [comment]
Working on this one now 👍

**Comment by ricburton** [comment]
Thanks George! True value add investor :)

**Comment by abstractpoint** [comment]
@ricburton No prob, I'm keen to do more if not for being a bit busy at the moment.. getting married in a few days!! 😊😁

**Comment by ricburton** [comment]
Congratulations! 🧖🏾‍♂️🧖🏼‍♀️
