### ISSUE TITLE
🇫🇷French

### ISSUE THREAD

**Issue by ricburton** [balance-io/balance-manager#304]
Bon!

**Comment by PierrickGT** [comment]
I can help on that one!
Is there any JSON file or spreadsheet where I could start the translation?

**Comment by ricburton** [comment]
Thanks Pierre!

Can you hop in the forum here?

https://spectrum.chat/thread/96247666-5578-418b-b557-2501895240a0

There is another community member who’s kindly offered to do this.

You can see how Russian was done here:

https://github.com/balance-io/balance-manager/pull/281/commits/be6e1f3312237e52f819f038fb19eee04fc9d8ad

I will write up a guide as soon as I can :)

**Comment by PierrickGT** [comment]
Thank you for the example.
I can create a `src/languages/_french.json` with the French translation in the coming days.

**Comment by TigerW1998** [comment]
Hi,

I've just completed the translation and I believe I've done the Github part of it correctly. Please let me know if something is awry, I would appreciate any feedback. Thank you to PierrickGT for offering to help, I appreciate it !

Best,

T.

**Comment by PierrickGT** [comment]
I've made some comment in your PR in order to add the French language to the dropdown menu.
Here is the link to the PR for reference : https://github.com/balance-io/balance-manager/pull/313

**Comment by PierrickGT** [comment]
@TigerW1998 I've taken your translation and created a PR in which I've included your translation and fixed the different lint errors.

**Comment by PierrickGT** [comment]
@ricburton this issue can be closed now
