### ISSUE TITLE
Cannot use more than 5 address when I use ledger

### ISSUE THREAD

**Issue by IvanBoutin** [balance-io/balance-manager#334]
### What is this issue about? (select one)

* [ X] Bug report
* [] Feature request
* [X ] Enhancement

### Issue Description

When i use balance manager with a Ledger, i cannot use more than the first five addresses. It's problematic for me, because I use more than five addresses with my ledger, so I can't see all my ether and my tokens. it's a problem with a lot of Dapp using ledger, so i don't if it's a bug or a enchancement :-)

### Expected Behavior

Add a way to display more than 5 address from a ledger

**Comment by ricburton** [comment]
We have had several complaints about this now. Let's get this one fixed ASAP.

**Comment by jinchung** [comment]
Hotfix for 20 addresses for now; will do a proper fix for fetching all the used up addresses later
