### ISSUE TITLE
Balance Manager Widget with iFrame support

### ISSUE THREAD

**Issue by rahulrumalla** [balance-io/balance-manager#357]
# Feature overview
Make Balance Manager compatible with iFrames so that the wallet can be _embedded_ into other sites as _widgets_. 

# Why?
Almost every web app that's working with web 3 will have to produce something that's very similar to what Balance has already done. This is growing is a full fledged wallet with some very interesting capabilities. Instead of re-inventing the wheel, embedding allows for adopting Manager's functionality *without* having the user leave the web app - retaining users' attention on the web app. 

# Examples
* [Spotify](https://developer.spotify.com/documentation/widgets/generate/play-button/)
* [Linkfire](https://kb.linkfire.com/hc/en-us/articles/115002662373-Widget-How-To-Embed-A-Linkfire-Campaign-On-Your-Website#examples)
* [Apple Music](https://widgets.itunes.apple.com/)

# Potential strategy & deliverables
1. Re-visit css config to support various versions like small/medium/large
2. Have an embed code generator ( see examples )

What do you guys think?

**Comment by ricburton** [comment]
Thanks for the suggestion! This is a huge security issue so we will not be doing this. However, we will be making Balance work on a variety of screen sizes.
