### ISSUE TITLE
Small style inconsistency for WalletConnect buttons

### ISSUE THREAD

**Issue by jackjdleslie** [balance-io/balance-manager#391]
### What is this issue about? (select one)

* [x] Bug report
* [ ] Feature request
* [ ] Enhancement

### Issue Description

Hover and active colours for the WalletConnect button (and the WalletConnect modal 'close' button) are the wrong colour scheme. They appear to be the colours for the Ledger button.

## Steps to reproduce

1. Hover over/click 'Use WalletConnect' button
2. Hover over/click 'Close' button on WalletConnect modal

### Expected Behavior

Should be blue colours

### Actual Behavior

Grey colours (Ledger theme)

**Comment by PierrickGT** [comment]
Fixed by this commit: https://github.com/balance-io/balance-manager/pull/390/commits/880ff676b45637859d041f94588b0ffc31422dd2

**Comment by jackjdleslie** [comment]
@PierrickGT update on this in PR #404
