### ISSUE TITLE
How do I add coin/token to exchange?

### ISSUE THREAD

**Issue by Ins0mniaIco** [balance-io/balance-manager#409]
### What is this issue about? (select one)

* [ ] Bug report
* [ x] Feature request
* [ x] Enhancement

## Steps to reproduce

1.  
2.  
3.  

### Actual Behavior

I want to add custom coins to the exchange, how can I do that?

**Comment by jinchung** [comment]
Hi, currently we use Shapeshift, so it will be determined by what is available through them. In the future, we will be adding other exchanges which will give us more exchange pairs.
