### ISSUE TITLE
Preparation for EIP-1102

### ISSUE THREAD

**Issue by jackjdleslie** [balance-io/balance-manager#430]
### What is this issue about? (select one)

* [ ] Bug report
* [ ] Feature request
* [x] Enhancement

### Issue Description

As per [this article](https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8) the web3 injection from MetaMask and other dapp browsers like Status, imToken and Mist will stop.

**Comment by cipherpeon** [comment]
Addressed in #431
