### ISSUE TITLE
WalletConnect fetch failure

### ISSUE THREAD

**Issue by jbibla** [balance-io/balance-manager#484]
### What is this issue about? (select one)

* [x] Bug report
* [ ] Feature request
* [ ] Enhancement

## Steps to reproduce

1.  go to manager.balance.io in chrome on a mac
2.  click "Use Wallet Connect"
3.  feel sad

### Expected Behavior

- clicking the WalletConnect button should display the QR code

### Actual Behavior

![Screen Shot 2019-04-24 at 6 38 32 PM](https://user-images.githubusercontent.com/6021933/56698527-31fe1580-66c0-11e9-8372-8103da5dec1c.png)

Thank you!

**Comment by jackjdleslie** [comment]
Thanks @jbibla! @pedrouid is in the process of upgrading WalletConnect so should be fixed soon 👍

**Comment by jackjdleslie** [comment]
Resolved with #470 and #487
