### ISSUE TITLE
Token Ticker mixup [telegram: @mihirjoshi23]

### ISSUE THREAD

**Issue by ricburton** [balance-io/balance-manager#60]
"hey Richard! I'm Mihir from Crypto Legitness. Just tried out the Balance app - it's gorgeous! Everything works great and I actually noticed that I had a lot of unaccounted money I didn't know I had, which was awesome. One piece of feedback I have would be that I have some tokens that have the same ticker as coins that exist but existed on different addresses before that token moved to another address. The app still associated a dollar value with that token and didn't check the actual erc20 address of that token - might be worth something looking into!"

asked for more info:

Richard Burton, [24 Mar 2018 at 17:29:38]:
ooh thanks

we rely on a third party data provider

we will be getting our own node

would you be comfortable sharing your ETH address?

so we can debug?

or which tokens are confused

**Comment by jinchung** [comment]
will be addressed with issue: https://github.com/balance-io/balance-manager/issues/339
